name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - ./ASP.net

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        path: ${{ matrix.projectPath }}/Library
    - name: Build
      run: dotnet build ./WebApplication1/WebApplication1.sln
      
    - name: Test
      run: dotnet test ./WebApplication1/WebApplication1.sln
